In [16]:
#Written Using Python 3

import numpy as np
import math

In [26]:
a=np.matrix([[3, -math.sqrt(2)],[ -math.sqrt(2), 2]])
a

matrix([[ 3.        , -1.41421356],
        [-1.41421356,  2.        ]])

In [28]:
eigval_a, eigvec_a=np.linalg.eig(a)
eigval_a, eigvec_a

(array([ 4.,  1.]), matrix([[ 0.81649658,  0.57735027],
         [-0.57735027,  0.81649658]]))

In [39]:
(eigvec_a[0]*eigvec_a[0].transpose())

matrix([[ 1.]])

In [40]:
(eigvec_a[1]*eigvec_a[1].transpose())

matrix([[ 1.]])

In [41]:
(eigvec_a[1]*eigvec_a[0].transpose())

matrix([[ 0.]])

In [42]:
(eigvec_a[0]*eigvec_a[1].transpose())

matrix([[ 0.]])