In [48]:
%matplotlib inline

from matplotlib import pyplot as plt
import pandas as pd
import numpy as np
from matplotlib.mlab import PCA as mlabPCA
from sklearn.decomposition import PCA as sklearnPCA

In [90]:
t=pd.read_csv('/Users/tokunbohiamang/Documents/github/tmh-scripts/statistics/applied_multivariate_statistical_analysis_problems/wichern_data/T5-8.dat', sep='\s+', header=None, skiprows=0);
#t=t.rename(columns={0:'jp_morgan', 1:'citibank', 2:'wells_fargo', 3:'royal', 4:'exxon'});

In [91]:
t.describe()

0            1            2             3            4
count    16.000000    16.000000    16.000000     16.000000    16.000000
mean   3557.750000  1478.437500  2676.875000  13563.625000   800.000000
std     606.535022  1182.815735  1207.701557   1303.197753   474.044302
min    2670.000000   344.000000  1175.000000  11367.000000   161.000000
25%    3132.500000   852.750000  1827.750000  12606.250000   284.000000
50%    3487.500000  1179.500000  2428.000000  13531.000000  1049.500000
75%    3690.500000  1804.750000  3388.000000  14870.750000  1188.500000
max    5217.000000  5326.000000  4675.000000  15482.000000  1385.000000

In [38]:
cov_t=t.cov()

In [88]:
cov_t

jp_morgan  citibank  wells_fargo     royal     exxon
jp_morgan     0.000433  0.000276     0.000159  0.000064  0.000089
citibank      0.000276  0.000439     0.000180  0.000181  0.000123
wells_fargo   0.000159  0.000180     0.000224  0.000073  0.000061
royal         0.000064  0.000181     0.000073  0.000722  0.000508
exxon         0.000089  0.000123     0.000061  0.000508  0.000766

In [39]:
w,v=np.linalg.eig(cov_t)

In [40]:
w #Eigenvalues

array([ 0.00136768,  0.00070116,  0.0002538 ,  0.0001426 ,  0.00011889])

In [41]:
v #Eigenvectors

array([[ 0.22282283,  0.62522603, -0.32611218, -0.662759  ,  0.11765952],
       [ 0.30728997,  0.57039003,  0.24959014,  0.4140935 , -0.58860803],
       [ 0.1548103 ,  0.34450492,  0.03763929,  0.49704993,  0.78030428],
       [ 0.63896798, -0.24794753,  0.64249741, -0.30886888,  0.14845546],
       [ 0.65090441, -0.32184779, -0.64586064,  0.21637575, -0.09371777]])

In [22]:
v

matrix([[-0.92387953,  0.38268343,  0.        ],
        [-0.38268343, -0.92387953,  0.        ],
        [ 0.        ,  0.        ,  1.        ]])

In [67]:
corr_t=t.corr()

In [68]:
a,b=np.linalg.eig(corr_t)

In [76]:
a

array([ 2.43727312,  1.40701266,  0.25516988,  0.50051275,  0.40003159])

In [70]:
b

array([[ 0.46908321,  0.36800696,  0.3841216 ,  0.60431522,  0.36302278],
       [ 0.53240549,  0.23646236, -0.49618794,  0.13610618, -0.6292079 ],
       [ 0.46516333,  0.3151795 ,  0.07116948, -0.7718281 ,  0.28896583],
       [ 0.38734594, -0.58503725,  0.59466408, -0.09336192, -0.38125151],
       [ 0.36068206, -0.60584628, -0.49755167,  0.10882629,  0.49341454]])

In [71]:
mlab_pca = mlabPCA(t)

In [82]:
mlab_pca.fracs

array([ 0.48745462,  0.28140253,  0.10010255,  0.08000632,  0.05103398])

In [49]:
sklearn_pca = sklearnPCA()

In [84]:
sklearn_transf = sklearn_pca.fit(t)

In [85]:
sklearn_pca.n_components_

5

In [86]:
sklearn_pca.explained_variance_ratio_

array([ 0.52926066,  0.27133298,  0.09821584,  0.055184  ,  0.04600652])

In [87]:
sklearn_pca.get_covariance()

array([[  4.29062956e-04,   2.72991513e-04,   1.57482576e-04,
          6.34967768e-05,   8.81024077e-05],
       [  2.72991513e-04,   4.34457814e-04,   1.78226373e-04,
          1.79689543e-04,   1.22065554e-04],
       [  1.57482576e-04,   1.78226373e-04,   2.21797706e-04,
          7.27007278e-05,   5.99582916e-05],
       [  6.34967768e-05,   1.79689543e-04,   7.27007278e-05,
          7.15481882e-04,   5.03342471e-04],
       [  8.81024077e-05,   1.22065554e-04,   5.99582916e-05,
          5.03342471e-04,   7.58240443e-04]])

In [89]:
sklearn_pca.get_params()

{'copy': True, 'n_components': None, 'whiten': False}